import React, { useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import MetaMaskIcon from "icons/metamask.svg";
import WalletConnectIcon from "icons/walletconnect.svg";

import { useMoralis } from "react-moralis";
import { Button } from "components/Button";

type LoginProvider = "metamask" | "walletconnect" | undefined;

const Home: NextPage = () => {
  const {
    authenticate,
    isAuthenticated,
    isAuthenticating,
    user,
    account,
    logout,
  } = useMoralis();

  useEffect(() => {
    if (isAuthenticated) {
      // add your logic here
    }
  }, [isAuthenticated]);

  const login = async (provider: LoginProvider) => {
    if (!isAuthenticated) {
      await authenticate({
        signingMessage: "Log in using Moralis",
        provider: provider,
      })
        .then(function (user) {
          console.log("logged in user:", user);
          console.log(user!.get("ethAddress"));
        })
        .catch(function (error) {
          console.log(error);
        });
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Welcome Web3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Moralis Hello World!</h1>

        <div className={styles.loginContainer}>
          {!isAuthenticated && (
            <>
              <Button
                className="loginButton"
                title="Login  Metamask"
                image={MetaMaskIcon}
                onClick={() => login("metamask")}
              />
              <Button
                className="loginButton"
                title="Login Wallet Connect"
                image={WalletConnectIcon}
                onClick={() => login("walletconnect")}
              />
            </>
          )}
          {isAuthenticated && (
            <>
              <Button className="loginButton" title="Logout" onClick={logout} />
            </>
          )}
        </div>
        <div className={styles.powered}></div>
        <a
          href="https://www.linkedin.com/in/agitt"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <span className={styles.logo}>Agit Isik</span>
        </a>
      </main>
    </div>
  );
};

export default Home;
